In [11]:
import pandas as pd
from sqlalchemy import create_engine

In [12]:
def get_engine():
    return create_engine(
        "mysql+mysqlconnector://root:GhostFace23@localhost/foodly"
    )

engine = get_engine()

In [13]:
requete_aliment = """
SELECT
    nom,
    marque,
    sucre,
    calories,
    graisses,
    proteines,
    bio
FROM aliment
"""

df_aliment = pd.read_sql(requete_aliment, engine)

df_aliment.head()

       nom       marque  sucre  calories  graisses  proteines  bio
0    pomme  sans marque   19.1        72       0.2        0.4    0
1    poire  sans marque   27.5       134       0.2        1.1    1
2   banane     chiquita   24.0       101       0.3        1.1    0
3   jambon        herta    0.2        34       0.8        6.6    0
4  compote       andros   11.0        51       0.0        0.5    0

In [14]:
df_user = pd.read_sql(
    "SELECT * FROM utilisateur",
    engine
)

df_user.head()

   id         nom   prenom             email  langue_id
0   1    durantay  quentin  qentin@gmail.com          1
1   2      dupont    marie  marie@hotmail.fr          1
2   3      miller  vincent      vm@yahoo.com          2
3   4  zuckerberg     marc    marc@gmail.com          2
4   5        paul   pierre      pp@orange.fr          1

In [15]:
df_aliment["bio"] = df_aliment["bio"].astype(float)

df_user["nom complet"] = (
    df_user["nom"] +
    " " +
    df_user["prenom"].fillna("")
).str.strip()

In [16]:
df_aliment.info()

df_user[["nom", "prenom", "nom complet"]].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nom        20 non-null     object
 1   marque     20 non-null     object
 2   sucre      20 non-null     float64
 3   calories   20 non-null     int64
 4   graisses   20 non-null     float64
 5   proteines  20 non-null     float64
 6   bio        20 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.2+ KB

          nom   prenom       nom complet
0    durantay  quentin  durantay quentin
1      dupont    marie      dupont marie
2      miller  vincent    miller vincent
3  zuckerberg     marc   zuckerberg marc
4        paul   pierre       paul pierre

In [17]:
df_aliment.describe()

           sucre    calories  graisses  proteines        bio
count  20.000000   20.000000  20.00000  20.000000  20.000000
mean   15.570000  109.000000   2.07000   6.330000   0.300000
std    16.568076   77.530979   3.09075   8.130132   0.470162
min     0.000000    0.000000   0.00000   0.000000   0.000000
25%     0.550000   71.000000   0.20000   1.100000   0.000000
50%    13.500000   99.000000   0.55000   2.750000   0.000000
75%    24.625000  131.000000   3.22500   6.825000   1.000000
max    64.000000  353.000000  12.30000  26.200000   1.000000

In [18]:
df_aliment["bio"].value_counts()

bio
0.0    14
1.0     6
Name: count, dtype: int64

In [19]:
df_user.shape

(10, 6)

In [10]:
df_aliment.to_sql(
    "aliment_git",
    con=engine,
    if_exists="replace",
    index=False
)

-1